name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install docker.io -y

    - name: Build Docker image
      run: docker build -t user-service .

    - name: Push Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag user-service ${{ secrets.DOCKER_USERNAME }}/user-service
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service
