name: CI/CD Pipeline for User Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build and tag Docker image
        run: |
          docker build -t user-service .
          docker tag user-service:latest <your-docker-username>/user-service:latest

      - name: Push Docker image to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push <your-docker-username>/user-service:latest

      - name: Deploy to Kubernetes
        uses: appleboy/kubernetes-action@master
        with:
          k8s_api_server: ${{ secrets.K8S_API_SERVER }}
          k8s_secret: ${{ secrets.K8S_SECRET }}
          k8s_config: ${{ secrets.K8S_CONFIG }}
          namespace: default
          image_name: <your-docker-username>/user-service
          image_tag: latest
